import type { NextPage } from 'next'
import Head from 'next/head'
import * as React from 'react'
import styles from '../styles/Home.module.css'

import Main from './main';
import { findFlagUrlByIso2Code } from "country-flags-svg";


const egFlag = findFlagUrlByIso2Code("EG");
const saFlag = findFlagUrlByIso2Code("SA");
const kwFlag = findFlagUrlByIso2Code("KW");


const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Tadarab Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
    </div>
  )
}


export default Home


